name: Publish Nuget Package

env:
    NUGET_PACKAGE_NAME_VERSION: "ShadowRoot.Digger.3.1.5.nupkg"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]
        dotnet-version: [ '3.1.x' ]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '3.1.x'
          
    - name: Create Package
      run: dotnet pack --configuration=Release ShadowRoot.Digger/ShadowRoot.Digger.csproj
      
    - name: Publish Nuget Package
      run: dotnet nuget push ShadowRoot.Digger/bin/Release/${{ env.NUGET_PACKAGE_NAME_VERSION }} -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      